### ISSUE TITLE
Generated Swagger is Empty

### ISSUE THREAD

**Issue by tomidix** [Azure/azure-functions-openapi-extension#269]
#225 
#157 
This one is still a problem (also on .net 5) if deployed on Azure Function via Azure DevOps..
As I see some fix was placed in code but there is still no new package available..

Publish new package..

**Comment by justinyoo** [comment]
Do you still experience the issue with 0.9.0-preview?

**Comment by tomidix** [comment]
This is now fixed in 0.9.0-preview. Works fine both locally ('func host start' command) and on Azure Functions (deployed via DevOps). 
Thank you very much.

**Comment by myddraall** [comment]
I am still seeing this issue with 0.9.0-preview.  I don't really know what I can attach to help with repro, but would be happy to reply as needed.  I have a netcoreapp3.1 azure functions v3 project in a solution, it works in debug, but not func start or via devops deployment.  I have tried adding and removing <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput> to the project, removed the deps.json from the referenced projects.  Any help would be appreciated.
